# Generated by Django 5.1.4 on 2024-12-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_rename_value_measurement_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
