# Generated by Django 5.1.2 on 2024-10-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.URLField(verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(verbose_name='slug_name'),
        ),
    ]
